package io.github.karunarathnad.immuto.example.advanced.sealed.mapper;

import io.github.karunarathnad.immuto.example.advanced.sealed.model.NotificationEventDTO;
import io.github.karunarathnad.immuto.example.advanced.sealed.model.NotificationEvent;

/**
 * Maps instances of the sealed {@link NotificationEvent} hierarchy to
 * their corresponding {@link NotificationEventDTO} representations.
 * <p>
 * Implementations (typically generated by Immuto) are expected to
 * exhaustively handle every permitted subtype of {@code NotificationEvent}
 * — currently
 * {@link io.github.karunarathnad.immuto.example.advanced.sealed.model.EmailEvent}
 * and
 * {@link io.github.karunarathnad.immuto.example.advanced.sealed.model.SmsEvent}
 * — mapping each to its respective DTO subtype
 * ({@link io.github.karunarathnad.immuto.example.advanced.sealed.dto.EmailEventDTO}
 * and
 * {@link io.github.karunarathnad.immuto.example.advanced.sealed.dto.SmsEventDTO})
 * without relying on a {@code default} branch. This exhaustiveness is
 * the key behavior this interface exists to verify.
 */
public interface NotificationEventMapper {

    /**
     * Maps a single {@link NotificationEvent} to its corresponding
     * {@link NotificationEventDTO}.
     *
     * @param event the domain event to map; must be a non-null instance
     *              of one of the permitted subtypes of
     *              {@code NotificationEvent}
     * @return the mapped DTO representation of the given event
     */
    NotificationEventDTO toDto(NotificationEvent event);
}